
namespace PlayerUI
{
    partial class ThongTinCacNhanVien
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ThongTinCacNhanVien));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.TextBoxDiaChi = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Avatar = new System.Windows.Forms.PictureBox();
            this.BtnTaiAnh = new Bunifu.Framework.UI.BunifuTileButton();
            this.TextBoxMaBoPhan = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.TextBoxSoDienThoai = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.labelNu = new System.Windows.Forms.Label();
            this.labelNam = new System.Windows.Forms.Label();
            this.bunifuTextBoxCMND = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.TextBoxTenNV = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.TextBoxMaNV = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.BtnRadioNu = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.BtnRadioNam = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.DatepickerNgaySinh = new Bunifu.Framework.UI.BunifuDatepicker();
            this.NgaySinh = new System.Windows.Forms.Label();
            this.BtnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnLuu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridViewNV = new System.Windows.Forms.DataGridView();
            this.bunifuTextBoxTimKiem = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.Avatar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewNV)).BeginInit();
            this.SuspendLayout();
            // 
            // TextBoxDiaChi
            // 
            this.TextBoxDiaChi.AcceptsReturn = false;
            this.TextBoxDiaChi.AcceptsTab = false;
            this.TextBoxDiaChi.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.TextBoxDiaChi.AnimationSpeed = 200;
            this.TextBoxDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxDiaChi.BackgroundImage")));
            this.TextBoxDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxDiaChi.BorderRadius = 1;
            this.TextBoxDiaChi.BorderThickness = 1;
            this.TextBoxDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxDiaChi.DefaultText = "";
            this.TextBoxDiaChi.FillColor = System.Drawing.Color.White;
            this.TextBoxDiaChi.HideSelection = true;
            this.TextBoxDiaChi.IconLeft = null;
            this.TextBoxDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDiaChi.IconPadding = 10;
            this.TextBoxDiaChi.IconRight = null;
            this.TextBoxDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDiaChi.Lines = new string[0];
            this.TextBoxDiaChi.Location = new System.Drawing.Point(23, 77);
            this.TextBoxDiaChi.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.TextBoxDiaChi.MaxLength = 32767;
            this.TextBoxDiaChi.MinimumSize = new System.Drawing.Size(89, 28);
            this.TextBoxDiaChi.Modified = false;
            this.TextBoxDiaChi.Multiline = false;
            this.TextBoxDiaChi.Name = "TextBoxDiaChi";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDiaChi.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDiaChi.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDiaChi.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDiaChi.OnIdleState = stateProperties4;
            this.TextBoxDiaChi.PasswordChar = '\0';
            this.TextBoxDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDiaChi.PlaceholderText = "Địa chỉ";
            this.TextBoxDiaChi.ReadOnly = false;
            this.TextBoxDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxDiaChi.SelectedText = "";
            this.TextBoxDiaChi.SelectionLength = 0;
            this.TextBoxDiaChi.SelectionStart = 0;
            this.TextBoxDiaChi.ShortcutsEnabled = true;
            this.TextBoxDiaChi.Size = new System.Drawing.Size(187, 28);
            this.TextBoxDiaChi.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxDiaChi.TabIndex = 48;
            this.TextBoxDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxDiaChi.TextMarginBottom = 0;
            this.TextBoxDiaChi.TextMarginLeft = 5;
            this.TextBoxDiaChi.TextMarginTop = 0;
            this.TextBoxDiaChi.TextPlaceholder = "Địa chỉ";
            this.TextBoxDiaChi.UseSystemPasswordChar = false;
            this.TextBoxDiaChi.WordWrap = true;
            // 
            // Avatar
            // 
            this.Avatar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.Avatar.Location = new System.Drawing.Point(492, 10);
            this.Avatar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Avatar.Name = "Avatar";
            this.Avatar.Size = new System.Drawing.Size(188, 134);
            this.Avatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.Avatar.TabIndex = 47;
            this.Avatar.TabStop = false;
            // 
            // BtnTaiAnh
            // 
            this.BtnTaiAnh.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnTaiAnh.BackColor = System.Drawing.Color.SeaGreen;
            this.BtnTaiAnh.color = System.Drawing.Color.SeaGreen;
            this.BtnTaiAnh.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.BtnTaiAnh.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnTaiAnh.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.BtnTaiAnh.ForeColor = System.Drawing.Color.White;
            this.BtnTaiAnh.Image = ((System.Drawing.Image)(resources.GetObject("BtnTaiAnh.Image")));
            this.BtnTaiAnh.ImagePosition = 14;
            this.BtnTaiAnh.ImageZoom = 50;
            this.BtnTaiAnh.LabelPosition = 29;
            this.BtnTaiAnh.LabelText = "Tải hình";
            this.BtnTaiAnh.Location = new System.Drawing.Point(493, 150);
            this.BtnTaiAnh.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.BtnTaiAnh.Name = "BtnTaiAnh";
            this.BtnTaiAnh.Size = new System.Drawing.Size(187, 28);
            this.BtnTaiAnh.TabIndex = 46;
            this.BtnTaiAnh.Click += new System.EventHandler(this.BtnTaiAnh_Click);
            // 
            // TextBoxMaBoPhan
            // 
            this.TextBoxMaBoPhan.AcceptsReturn = false;
            this.TextBoxMaBoPhan.AcceptsTab = false;
            this.TextBoxMaBoPhan.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.TextBoxMaBoPhan.AnimationSpeed = 200;
            this.TextBoxMaBoPhan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxMaBoPhan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxMaBoPhan.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxMaBoPhan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxMaBoPhan.BackgroundImage")));
            this.TextBoxMaBoPhan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxMaBoPhan.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxMaBoPhan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxMaBoPhan.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxMaBoPhan.BorderRadius = 1;
            this.TextBoxMaBoPhan.BorderThickness = 1;
            this.TextBoxMaBoPhan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxMaBoPhan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxMaBoPhan.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxMaBoPhan.DefaultText = "";
            this.TextBoxMaBoPhan.FillColor = System.Drawing.Color.White;
            this.TextBoxMaBoPhan.HideSelection = true;
            this.TextBoxMaBoPhan.IconLeft = null;
            this.TextBoxMaBoPhan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxMaBoPhan.IconPadding = 10;
            this.TextBoxMaBoPhan.IconRight = null;
            this.TextBoxMaBoPhan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxMaBoPhan.Lines = new string[0];
            this.TextBoxMaBoPhan.Location = new System.Drawing.Point(225, 41);
            this.TextBoxMaBoPhan.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.TextBoxMaBoPhan.MaxLength = 32767;
            this.TextBoxMaBoPhan.MinimumSize = new System.Drawing.Size(89, 28);
            this.TextBoxMaBoPhan.Modified = false;
            this.TextBoxMaBoPhan.Multiline = false;
            this.TextBoxMaBoPhan.Name = "TextBoxMaBoPhan";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxMaBoPhan.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxMaBoPhan.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxMaBoPhan.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxMaBoPhan.OnIdleState = stateProperties8;
            this.TextBoxMaBoPhan.PasswordChar = '\0';
            this.TextBoxMaBoPhan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxMaBoPhan.PlaceholderText = "Mã bộ phận";
            this.TextBoxMaBoPhan.ReadOnly = false;
            this.TextBoxMaBoPhan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxMaBoPhan.SelectedText = "";
            this.TextBoxMaBoPhan.SelectionLength = 0;
            this.TextBoxMaBoPhan.SelectionStart = 0;
            this.TextBoxMaBoPhan.ShortcutsEnabled = true;
            this.TextBoxMaBoPhan.Size = new System.Drawing.Size(187, 28);
            this.TextBoxMaBoPhan.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxMaBoPhan.TabIndex = 43;
            this.TextBoxMaBoPhan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxMaBoPhan.TextMarginBottom = 0;
            this.TextBoxMaBoPhan.TextMarginLeft = 5;
            this.TextBoxMaBoPhan.TextMarginTop = 0;
            this.TextBoxMaBoPhan.TextPlaceholder = "Mã bộ phận";
            this.TextBoxMaBoPhan.UseSystemPasswordChar = false;
            this.TextBoxMaBoPhan.WordWrap = true;
            // 
            // TextBoxSoDienThoai
            // 
            this.TextBoxSoDienThoai.AcceptsReturn = false;
            this.TextBoxSoDienThoai.AcceptsTab = false;
            this.TextBoxSoDienThoai.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.TextBoxSoDienThoai.AnimationSpeed = 200;
            this.TextBoxSoDienThoai.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxSoDienThoai.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxSoDienThoai.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxSoDienThoai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxSoDienThoai.BackgroundImage")));
            this.TextBoxSoDienThoai.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxSoDienThoai.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxSoDienThoai.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxSoDienThoai.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxSoDienThoai.BorderRadius = 1;
            this.TextBoxSoDienThoai.BorderThickness = 1;
            this.TextBoxSoDienThoai.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxSoDienThoai.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSoDienThoai.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxSoDienThoai.DefaultText = "";
            this.TextBoxSoDienThoai.FillColor = System.Drawing.Color.White;
            this.TextBoxSoDienThoai.HideSelection = true;
            this.TextBoxSoDienThoai.IconLeft = null;
            this.TextBoxSoDienThoai.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSoDienThoai.IconPadding = 10;
            this.TextBoxSoDienThoai.IconRight = null;
            this.TextBoxSoDienThoai.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSoDienThoai.Lines = new string[0];
            this.TextBoxSoDienThoai.Location = new System.Drawing.Point(225, 77);
            this.TextBoxSoDienThoai.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.TextBoxSoDienThoai.MaxLength = 32767;
            this.TextBoxSoDienThoai.MinimumSize = new System.Drawing.Size(89, 28);
            this.TextBoxSoDienThoai.Modified = false;
            this.TextBoxSoDienThoai.Multiline = false;
            this.TextBoxSoDienThoai.Name = "TextBoxSoDienThoai";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSoDienThoai.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSoDienThoai.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSoDienThoai.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSoDienThoai.OnIdleState = stateProperties12;
            this.TextBoxSoDienThoai.PasswordChar = '\0';
            this.TextBoxSoDienThoai.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSoDienThoai.PlaceholderText = "Số điện thoại";
            this.TextBoxSoDienThoai.ReadOnly = false;
            this.TextBoxSoDienThoai.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxSoDienThoai.SelectedText = "";
            this.TextBoxSoDienThoai.SelectionLength = 0;
            this.TextBoxSoDienThoai.SelectionStart = 0;
            this.TextBoxSoDienThoai.ShortcutsEnabled = true;
            this.TextBoxSoDienThoai.Size = new System.Drawing.Size(187, 28);
            this.TextBoxSoDienThoai.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxSoDienThoai.TabIndex = 40;
            this.TextBoxSoDienThoai.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxSoDienThoai.TextMarginBottom = 0;
            this.TextBoxSoDienThoai.TextMarginLeft = 5;
            this.TextBoxSoDienThoai.TextMarginTop = 0;
            this.TextBoxSoDienThoai.TextPlaceholder = "Số điện thoại";
            this.TextBoxSoDienThoai.UseSystemPasswordChar = false;
            this.TextBoxSoDienThoai.WordWrap = true;
            // 
            // labelNu
            // 
            this.labelNu.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.labelNu.AutoSize = true;
            this.labelNu.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.labelNu.Location = new System.Drawing.Point(308, 118);
            this.labelNu.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.labelNu.Name = "labelNu";
            this.labelNu.Size = new System.Drawing.Size(34, 23);
            this.labelNu.TabIndex = 39;
            this.labelNu.Text = "Nữ";
            // 
            // labelNam
            // 
            this.labelNam.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.labelNam.AutoSize = true;
            this.labelNam.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.labelNam.Location = new System.Drawing.Point(122, 118);
            this.labelNam.Name = "labelNam";
            this.labelNam.Size = new System.Drawing.Size(47, 23);
            this.labelNam.TabIndex = 38;
            this.labelNam.Text = "Nam";
            // 
            // bunifuTextBoxCMND
            // 
            this.bunifuTextBoxCMND.AcceptsReturn = false;
            this.bunifuTextBoxCMND.AcceptsTab = false;
            this.bunifuTextBoxCMND.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuTextBoxCMND.AnimationSpeed = 200;
            this.bunifuTextBoxCMND.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxCMND.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxCMND.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxCMND.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxCMND.BackgroundImage")));
            this.bunifuTextBoxCMND.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxCMND.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.bunifuTextBoxCMND.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxCMND.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxCMND.BorderRadius = 1;
            this.bunifuTextBoxCMND.BorderThickness = 1;
            this.bunifuTextBoxCMND.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxCMND.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCMND.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuTextBoxCMND.DefaultText = "";
            this.bunifuTextBoxCMND.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxCMND.HideSelection = true;
            this.bunifuTextBoxCMND.IconLeft = null;
            this.bunifuTextBoxCMND.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCMND.IconPadding = 10;
            this.bunifuTextBoxCMND.IconRight = null;
            this.bunifuTextBoxCMND.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCMND.Lines = new string[0];
            this.bunifuTextBoxCMND.Location = new System.Drawing.Point(23, 41);
            this.bunifuTextBoxCMND.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.bunifuTextBoxCMND.MaxLength = 32767;
            this.bunifuTextBoxCMND.MinimumSize = new System.Drawing.Size(89, 28);
            this.bunifuTextBoxCMND.Modified = false;
            this.bunifuTextBoxCMND.Multiline = false;
            this.bunifuTextBoxCMND.Name = "bunifuTextBoxCMND";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCMND.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxCMND.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCMND.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCMND.OnIdleState = stateProperties16;
            this.bunifuTextBoxCMND.PasswordChar = '\0';
            this.bunifuTextBoxCMND.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxCMND.PlaceholderText = "Chứng minh nhân dân";
            this.bunifuTextBoxCMND.ReadOnly = false;
            this.bunifuTextBoxCMND.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxCMND.SelectedText = "";
            this.bunifuTextBoxCMND.SelectionLength = 0;
            this.bunifuTextBoxCMND.SelectionStart = 0;
            this.bunifuTextBoxCMND.ShortcutsEnabled = true;
            this.bunifuTextBoxCMND.Size = new System.Drawing.Size(187, 28);
            this.bunifuTextBoxCMND.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxCMND.TabIndex = 37;
            this.bunifuTextBoxCMND.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxCMND.TextMarginBottom = 0;
            this.bunifuTextBoxCMND.TextMarginLeft = 5;
            this.bunifuTextBoxCMND.TextMarginTop = 0;
            this.bunifuTextBoxCMND.TextPlaceholder = "Chứng minh nhân dân";
            this.bunifuTextBoxCMND.UseSystemPasswordChar = false;
            this.bunifuTextBoxCMND.WordWrap = true;
            // 
            // TextBoxTenNV
            // 
            this.TextBoxTenNV.AcceptsReturn = false;
            this.TextBoxTenNV.AcceptsTab = false;
            this.TextBoxTenNV.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.TextBoxTenNV.AnimationSpeed = 200;
            this.TextBoxTenNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxTenNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxTenNV.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxTenNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxTenNV.BackgroundImage")));
            this.TextBoxTenNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxTenNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxTenNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxTenNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxTenNV.BorderRadius = 1;
            this.TextBoxTenNV.BorderThickness = 1;
            this.TextBoxTenNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxTenNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTenNV.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxTenNV.DefaultText = "";
            this.TextBoxTenNV.FillColor = System.Drawing.Color.White;
            this.TextBoxTenNV.HideSelection = true;
            this.TextBoxTenNV.IconLeft = null;
            this.TextBoxTenNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTenNV.IconPadding = 10;
            this.TextBoxTenNV.IconRight = null;
            this.TextBoxTenNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTenNV.Lines = new string[0];
            this.TextBoxTenNV.Location = new System.Drawing.Point(23, 6);
            this.TextBoxTenNV.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.TextBoxTenNV.MaxLength = 32767;
            this.TextBoxTenNV.MinimumSize = new System.Drawing.Size(89, 28);
            this.TextBoxTenNV.Modified = false;
            this.TextBoxTenNV.Multiline = false;
            this.TextBoxTenNV.Name = "TextBoxTenNV";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTenNV.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTenNV.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTenNV.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTenNV.OnIdleState = stateProperties20;
            this.TextBoxTenNV.PasswordChar = '\0';
            this.TextBoxTenNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTenNV.PlaceholderText = "Tên nhân viên";
            this.TextBoxTenNV.ReadOnly = false;
            this.TextBoxTenNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxTenNV.SelectedText = "";
            this.TextBoxTenNV.SelectionLength = 0;
            this.TextBoxTenNV.SelectionStart = 0;
            this.TextBoxTenNV.ShortcutsEnabled = true;
            this.TextBoxTenNV.Size = new System.Drawing.Size(187, 28);
            this.TextBoxTenNV.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxTenNV.TabIndex = 36;
            this.TextBoxTenNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxTenNV.TextMarginBottom = 0;
            this.TextBoxTenNV.TextMarginLeft = 5;
            this.TextBoxTenNV.TextMarginTop = 0;
            this.TextBoxTenNV.TextPlaceholder = "Tên nhân viên";
            this.TextBoxTenNV.UseSystemPasswordChar = false;
            this.TextBoxTenNV.WordWrap = true;
            // 
            // TextBoxMaNV
            // 
            this.TextBoxMaNV.AcceptsReturn = false;
            this.TextBoxMaNV.AcceptsTab = false;
            this.TextBoxMaNV.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.TextBoxMaNV.AnimationSpeed = 200;
            this.TextBoxMaNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxMaNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxMaNV.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxMaNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxMaNV.BackgroundImage")));
            this.TextBoxMaNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxMaNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxMaNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxMaNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxMaNV.BorderRadius = 1;
            this.TextBoxMaNV.BorderThickness = 1;
            this.TextBoxMaNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxMaNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxMaNV.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxMaNV.DefaultText = "";
            this.TextBoxMaNV.FillColor = System.Drawing.Color.White;
            this.TextBoxMaNV.HideSelection = true;
            this.TextBoxMaNV.IconLeft = null;
            this.TextBoxMaNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxMaNV.IconPadding = 10;
            this.TextBoxMaNV.IconRight = null;
            this.TextBoxMaNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxMaNV.Lines = new string[0];
            this.TextBoxMaNV.Location = new System.Drawing.Point(225, 6);
            this.TextBoxMaNV.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.TextBoxMaNV.MaxLength = 32767;
            this.TextBoxMaNV.MinimumSize = new System.Drawing.Size(89, 28);
            this.TextBoxMaNV.Modified = false;
            this.TextBoxMaNV.Multiline = false;
            this.TextBoxMaNV.Name = "TextBoxMaNV";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxMaNV.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxMaNV.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxMaNV.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxMaNV.OnIdleState = stateProperties24;
            this.TextBoxMaNV.PasswordChar = '\0';
            this.TextBoxMaNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxMaNV.PlaceholderText = "Mã Nhân Viên";
            this.TextBoxMaNV.ReadOnly = false;
            this.TextBoxMaNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxMaNV.SelectedText = "";
            this.TextBoxMaNV.SelectionLength = 0;
            this.TextBoxMaNV.SelectionStart = 0;
            this.TextBoxMaNV.ShortcutsEnabled = true;
            this.TextBoxMaNV.Size = new System.Drawing.Size(187, 28);
            this.TextBoxMaNV.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxMaNV.TabIndex = 35;
            this.TextBoxMaNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxMaNV.TextMarginBottom = 0;
            this.TextBoxMaNV.TextMarginLeft = 5;
            this.TextBoxMaNV.TextMarginTop = 0;
            this.TextBoxMaNV.TextPlaceholder = "Mã Nhân Viên";
            this.TextBoxMaNV.UseSystemPasswordChar = false;
            this.TextBoxMaNV.WordWrap = true;
            // 
            // BtnRadioNu
            // 
            this.BtnRadioNu.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnRadioNu.Checked = false;
            this.BtnRadioNu.Location = new System.Drawing.Point(273, 114);
            this.BtnRadioNu.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.BtnRadioNu.Name = "BtnRadioNu";
            this.BtnRadioNu.OutlineColor = System.Drawing.Color.Purple;
            this.BtnRadioNu.RadioColor = System.Drawing.Color.Purple;
            this.BtnRadioNu.Size = new System.Drawing.Size(27, 27);
            this.BtnRadioNu.TabIndex = 34;
            this.BtnRadioNu.Text = null;
            // 
            // BtnRadioNam
            // 
            this.BtnRadioNam.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnRadioNam.Checked = true;
            this.BtnRadioNam.Location = new System.Drawing.Point(90, 113);
            this.BtnRadioNam.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.BtnRadioNam.Name = "BtnRadioNam";
            this.BtnRadioNam.OutlineColor = System.Drawing.Color.Purple;
            this.BtnRadioNam.RadioColor = System.Drawing.Color.Purple;
            this.BtnRadioNam.Size = new System.Drawing.Size(27, 27);
            this.BtnRadioNam.TabIndex = 33;
            this.BtnRadioNam.Text = null;
            // 
            // DatepickerNgaySinh
            // 
            this.DatepickerNgaySinh.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.DatepickerNgaySinh.BackColor = System.Drawing.Color.SeaGreen;
            this.DatepickerNgaySinh.BorderRadius = 0;
            this.DatepickerNgaySinh.ForeColor = System.Drawing.Color.White;
            this.DatepickerNgaySinh.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            this.DatepickerNgaySinh.FormatCustom = null;
            this.DatepickerNgaySinh.Location = new System.Drawing.Point(168, 152);
            this.DatepickerNgaySinh.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.DatepickerNgaySinh.Name = "DatepickerNgaySinh";
            this.DatepickerNgaySinh.Size = new System.Drawing.Size(244, 28);
            this.DatepickerNgaySinh.TabIndex = 51;
            this.DatepickerNgaySinh.Value = new System.DateTime(2021, 4, 25, 19, 51, 51, 815);
            // 
            // NgaySinh
            // 
            this.NgaySinh.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.NgaySinh.BackColor = System.Drawing.Color.SeaGreen;
            this.NgaySinh.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.NgaySinh.ForeColor = System.Drawing.Color.White;
            this.NgaySinh.Location = new System.Drawing.Point(25, 152);
            this.NgaySinh.Name = "NgaySinh";
            this.NgaySinh.Size = new System.Drawing.Size(191, 27);
            this.NgaySinh.TabIndex = 50;
            this.NgaySinh.Text = " Ngày sinh";
            this.NgaySinh.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // BtnThem
            // 
            this.BtnThem.AllowToggling = false;
            this.BtnThem.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnThem.AnimationSpeed = 200;
            this.BtnThem.AutoGenerateColors = false;
            this.BtnThem.BackColor = System.Drawing.Color.Transparent;
            this.BtnThem.BackColor1 = System.Drawing.Color.ForestGreen;
            this.BtnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnThem.BackgroundImage")));
            this.BtnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThem.ButtonText = "Thêm";
            this.BtnThem.ButtonTextMarginLeft = 0;
            this.BtnThem.ColorContrastOnClick = 45;
            this.BtnThem.ColorContrastOnHover = 45;
            this.BtnThem.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnThem.CustomizableEdges = borderEdges1;
            this.BtnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnThem.DisabledBorderColor = System.Drawing.Color.Empty;
            this.BtnThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnThem.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.BtnThem.ForeColor = System.Drawing.Color.White;
            this.BtnThem.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnThem.IconMarginLeft = 11;
            this.BtnThem.IconPadding = 10;
            this.BtnThem.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnThem.IdleBorderColor = System.Drawing.Color.OliveDrab;
            this.BtnThem.IdleBorderRadius = 3;
            this.BtnThem.IdleBorderThickness = 1;
            this.BtnThem.IdleFillColor = System.Drawing.Color.ForestGreen;
            this.BtnThem.IdleIconLeftImage = null;
            this.BtnThem.IdleIconRightImage = null;
            this.BtnThem.IndicateFocus = false;
            this.BtnThem.Location = new System.Drawing.Point(440, 186);
            this.BtnThem.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.BtnThem.Name = "BtnThem";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.BorderRadius = 3;
            stateProperties25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties25.BorderThickness = 1;
            stateProperties25.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.IconLeftImage = null;
            stateProperties25.IconRightImage = null;
            this.BtnThem.onHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties26.BorderRadius = 3;
            stateProperties26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties26.BorderThickness = 1;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties26.ForeColor = System.Drawing.Color.White;
            stateProperties26.IconLeftImage = null;
            stateProperties26.IconRightImage = null;
            this.BtnThem.OnPressedState = stateProperties26;
            this.BtnThem.Size = new System.Drawing.Size(62, 28);
            this.BtnThem.TabIndex = 55;
            this.BtnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnThem.TextMarginLeft = 0;
            this.BtnThem.UseDefaultRadiusAndThickness = true;
            this.BtnThem.Click += new System.EventHandler(this.BtnThem_Click);
            // 
            // BtnLuu
            // 
            this.BtnLuu.AllowToggling = false;
            this.BtnLuu.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnLuu.AnimationSpeed = 200;
            this.BtnLuu.AutoGenerateColors = false;
            this.BtnLuu.BackColor = System.Drawing.Color.Transparent;
            this.BtnLuu.BackColor1 = System.Drawing.Color.ForestGreen;
            this.BtnLuu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnLuu.BackgroundImage")));
            this.BtnLuu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLuu.ButtonText = "Tải lại";
            this.BtnLuu.ButtonTextMarginLeft = 0;
            this.BtnLuu.ColorContrastOnClick = 45;
            this.BtnLuu.ColorContrastOnHover = 45;
            this.BtnLuu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnLuu.CustomizableEdges = borderEdges2;
            this.BtnLuu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnLuu.DisabledBorderColor = System.Drawing.Color.Empty;
            this.BtnLuu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLuu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLuu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnLuu.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.BtnLuu.ForeColor = System.Drawing.Color.White;
            this.BtnLuu.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnLuu.IconMarginLeft = 11;
            this.BtnLuu.IconPadding = 10;
            this.BtnLuu.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnLuu.IdleBorderColor = System.Drawing.Color.OliveDrab;
            this.BtnLuu.IdleBorderRadius = 3;
            this.BtnLuu.IdleBorderThickness = 1;
            this.BtnLuu.IdleFillColor = System.Drawing.Color.ForestGreen;
            this.BtnLuu.IdleIconLeftImage = null;
            this.BtnLuu.IdleIconRightImage = null;
            this.BtnLuu.IndicateFocus = false;
            this.BtnLuu.Location = new System.Drawing.Point(662, 186);
            this.BtnLuu.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.BtnLuu.Name = "BtnLuu";
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.BorderRadius = 3;
            stateProperties27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties27.BorderThickness = 1;
            stateProperties27.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.ForeColor = System.Drawing.Color.White;
            stateProperties27.IconLeftImage = null;
            stateProperties27.IconRightImage = null;
            this.BtnLuu.onHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties28.BorderRadius = 3;
            stateProperties28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties28.BorderThickness = 1;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.IconLeftImage = null;
            stateProperties28.IconRightImage = null;
            this.BtnLuu.OnPressedState = stateProperties28;
            this.BtnLuu.Size = new System.Drawing.Size(62, 28);
            this.BtnLuu.TabIndex = 56;
            this.BtnLuu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnLuu.TextMarginLeft = 0;
            this.BtnLuu.UseDefaultRadiusAndThickness = true;
            this.BtnLuu.Click += new System.EventHandler(this.BtnLuu_Click);
            // 
            // BtnSua
            // 
            this.BtnSua.AllowToggling = false;
            this.BtnSua.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnSua.AnimationSpeed = 200;
            this.BtnSua.AutoGenerateColors = false;
            this.BtnSua.BackColor = System.Drawing.Color.Transparent;
            this.BtnSua.BackColor1 = System.Drawing.Color.ForestGreen;
            this.BtnSua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSua.BackgroundImage")));
            this.BtnSua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSua.ButtonText = "Sữa";
            this.BtnSua.ButtonTextMarginLeft = 0;
            this.BtnSua.ColorContrastOnClick = 45;
            this.BtnSua.ColorContrastOnHover = 45;
            this.BtnSua.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnSua.CustomizableEdges = borderEdges3;
            this.BtnSua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSua.DisabledBorderColor = System.Drawing.Color.Empty;
            this.BtnSua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSua.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.BtnSua.ForeColor = System.Drawing.Color.White;
            this.BtnSua.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnSua.IconMarginLeft = 11;
            this.BtnSua.IconPadding = 10;
            this.BtnSua.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnSua.IdleBorderColor = System.Drawing.Color.OliveDrab;
            this.BtnSua.IdleBorderRadius = 3;
            this.BtnSua.IdleBorderThickness = 1;
            this.BtnSua.IdleFillColor = System.Drawing.Color.ForestGreen;
            this.BtnSua.IdleIconLeftImage = null;
            this.BtnSua.IdleIconRightImage = null;
            this.BtnSua.IndicateFocus = false;
            this.BtnSua.Location = new System.Drawing.Point(508, 186);
            this.BtnSua.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.BtnSua.Name = "BtnSua";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.BorderRadius = 3;
            stateProperties29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties29.BorderThickness = 1;
            stateProperties29.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.ForeColor = System.Drawing.Color.White;
            stateProperties29.IconLeftImage = null;
            stateProperties29.IconRightImage = null;
            this.BtnSua.onHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties30.BorderRadius = 3;
            stateProperties30.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties30.BorderThickness = 1;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties30.ForeColor = System.Drawing.Color.White;
            stateProperties30.IconLeftImage = null;
            stateProperties30.IconRightImage = null;
            this.BtnSua.OnPressedState = stateProperties30;
            this.BtnSua.Size = new System.Drawing.Size(62, 28);
            this.BtnSua.TabIndex = 57;
            this.BtnSua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnSua.TextMarginLeft = 0;
            this.BtnSua.UseDefaultRadiusAndThickness = true;
            this.BtnSua.Click += new System.EventHandler(this.BtnSua_Click);
            // 
            // BtnXoa
            // 
            this.BtnXoa.AllowToggling = false;
            this.BtnXoa.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnXoa.AnimationSpeed = 200;
            this.BtnXoa.AutoGenerateColors = false;
            this.BtnXoa.BackColor = System.Drawing.Color.Transparent;
            this.BtnXoa.BackColor1 = System.Drawing.Color.ForestGreen;
            this.BtnXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnXoa.BackgroundImage")));
            this.BtnXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnXoa.ButtonText = "Xóa";
            this.BtnXoa.ButtonTextMarginLeft = 0;
            this.BtnXoa.ColorContrastOnClick = 45;
            this.BtnXoa.ColorContrastOnHover = 45;
            this.BtnXoa.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnXoa.CustomizableEdges = borderEdges4;
            this.BtnXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnXoa.DisabledBorderColor = System.Drawing.Color.Empty;
            this.BtnXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnXoa.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.BtnXoa.ForeColor = System.Drawing.Color.White;
            this.BtnXoa.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnXoa.IconMarginLeft = 11;
            this.BtnXoa.IconPadding = 10;
            this.BtnXoa.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.BtnXoa.IdleBorderColor = System.Drawing.Color.OliveDrab;
            this.BtnXoa.IdleBorderRadius = 3;
            this.BtnXoa.IdleBorderThickness = 1;
            this.BtnXoa.IdleFillColor = System.Drawing.Color.ForestGreen;
            this.BtnXoa.IdleIconLeftImage = null;
            this.BtnXoa.IdleIconRightImage = null;
            this.BtnXoa.IndicateFocus = false;
            this.BtnXoa.Location = new System.Drawing.Point(594, 186);
            this.BtnXoa.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.BtnXoa.Name = "BtnXoa";
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.BorderRadius = 3;
            stateProperties31.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties31.BorderThickness = 1;
            stateProperties31.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.ForeColor = System.Drawing.Color.White;
            stateProperties31.IconLeftImage = null;
            stateProperties31.IconRightImage = null;
            this.BtnXoa.onHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties32.BorderRadius = 3;
            stateProperties32.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties32.BorderThickness = 1;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.IconLeftImage = null;
            stateProperties32.IconRightImage = null;
            this.BtnXoa.OnPressedState = stateProperties32;
            this.BtnXoa.Size = new System.Drawing.Size(62, 28);
            this.BtnXoa.TabIndex = 58;
            this.BtnXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnXoa.TextMarginLeft = 0;
            this.BtnXoa.UseDefaultRadiusAndThickness = true;
            this.BtnXoa.Click += new System.EventHandler(this.BtnXoa_Click);
            // 
            // dataGridViewNV
            // 
            this.dataGridViewNV.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.dataGridViewNV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewNV.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridViewNV.Location = new System.Drawing.Point(23, 224);
            this.dataGridViewNV.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dataGridViewNV.Name = "dataGridViewNV";
            this.dataGridViewNV.RowHeadersWidth = 62;
            this.dataGridViewNV.RowTemplate.Height = 28;
            this.dataGridViewNV.Size = new System.Drawing.Size(700, 206);
            this.dataGridViewNV.TabIndex = 59;
            this.dataGridViewNV.Click += new System.EventHandler(this.dataGridViewNV_Click);
            // 
            // bunifuTextBoxTimKiem
            // 
            this.bunifuTextBoxTimKiem.AcceptsReturn = false;
            this.bunifuTextBoxTimKiem.AcceptsTab = false;
            this.bunifuTextBoxTimKiem.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuTextBoxTimKiem.AnimationSpeed = 200;
            this.bunifuTextBoxTimKiem.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxTimKiem.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxTimKiem.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxTimKiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxTimKiem.BackgroundImage")));
            this.bunifuTextBoxTimKiem.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxTimKiem.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.bunifuTextBoxTimKiem.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxTimKiem.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxTimKiem.BorderRadius = 1;
            this.bunifuTextBoxTimKiem.BorderThickness = 1;
            this.bunifuTextBoxTimKiem.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxTimKiem.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxTimKiem.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuTextBoxTimKiem.DefaultText = "";
            this.bunifuTextBoxTimKiem.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxTimKiem.HideSelection = true;
            this.bunifuTextBoxTimKiem.IconLeft = null;
            this.bunifuTextBoxTimKiem.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxTimKiem.IconPadding = 10;
            this.bunifuTextBoxTimKiem.IconRight = null;
            this.bunifuTextBoxTimKiem.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxTimKiem.Lines = new string[0];
            this.bunifuTextBoxTimKiem.Location = new System.Drawing.Point(23, 186);
            this.bunifuTextBoxTimKiem.Margin = new System.Windows.Forms.Padding(36, 32, 36, 32);
            this.bunifuTextBoxTimKiem.MaxLength = 32767;
            this.bunifuTextBoxTimKiem.MinimumSize = new System.Drawing.Size(89, 28);
            this.bunifuTextBoxTimKiem.Modified = false;
            this.bunifuTextBoxTimKiem.Multiline = false;
            this.bunifuTextBoxTimKiem.Name = "bunifuTextBoxTimKiem";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxTimKiem.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Empty;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxTimKiem.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxTimKiem.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxTimKiem.OnIdleState = stateProperties36;
            this.bunifuTextBoxTimKiem.PasswordChar = '\0';
            this.bunifuTextBoxTimKiem.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxTimKiem.PlaceholderText = "Tìm kiếm theo mã nhân viên, tên, địa chỉ";
            this.bunifuTextBoxTimKiem.ReadOnly = false;
            this.bunifuTextBoxTimKiem.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxTimKiem.SelectedText = "";
            this.bunifuTextBoxTimKiem.SelectionLength = 0;
            this.bunifuTextBoxTimKiem.SelectionStart = 0;
            this.bunifuTextBoxTimKiem.ShortcutsEnabled = true;
            this.bunifuTextBoxTimKiem.Size = new System.Drawing.Size(389, 28);
            this.bunifuTextBoxTimKiem.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxTimKiem.TabIndex = 60;
            this.bunifuTextBoxTimKiem.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxTimKiem.TextMarginBottom = 0;
            this.bunifuTextBoxTimKiem.TextMarginLeft = 5;
            this.bunifuTextBoxTimKiem.TextMarginTop = 0;
            this.bunifuTextBoxTimKiem.TextPlaceholder = "Tìm kiếm theo mã nhân viên, tên, địa chỉ";
            this.bunifuTextBoxTimKiem.UseSystemPasswordChar = false;
            this.bunifuTextBoxTimKiem.WordWrap = true;
            this.bunifuTextBoxTimKiem.TextChanged += new System.EventHandler(this.bunifuTextBoxTimKiem_TextChanged);
            // 
            // ThongTinCacNhanVien
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(736, 442);
            this.Controls.Add(this.bunifuTextBoxTimKiem);
            this.Controls.Add(this.dataGridViewNV);
            this.Controls.Add(this.BtnXoa);
            this.Controls.Add(this.BtnSua);
            this.Controls.Add(this.BtnLuu);
            this.Controls.Add(this.BtnThem);
            this.Controls.Add(this.DatepickerNgaySinh);
            this.Controls.Add(this.NgaySinh);
            this.Controls.Add(this.TextBoxDiaChi);
            this.Controls.Add(this.Avatar);
            this.Controls.Add(this.BtnTaiAnh);
            this.Controls.Add(this.TextBoxMaBoPhan);
            this.Controls.Add(this.TextBoxSoDienThoai);
            this.Controls.Add(this.labelNu);
            this.Controls.Add(this.labelNam);
            this.Controls.Add(this.bunifuTextBoxCMND);
            this.Controls.Add(this.TextBoxTenNV);
            this.Controls.Add(this.TextBoxMaNV);
            this.Controls.Add(this.BtnRadioNu);
            this.Controls.Add(this.BtnRadioNam);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "ThongTinCacNhanVien";
            this.Text = "ThongTinNhanVien";
            this.Load += new System.EventHandler(this.ThongTinCacNhanVien_Load);
            ((System.ComponentModel.ISupportInitialize)(this.Avatar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewNV)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxDiaChi;
        private System.Windows.Forms.PictureBox Avatar;
        private Bunifu.Framework.UI.BunifuTileButton BtnTaiAnh;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxMaBoPhan;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxSoDienThoai;
        private System.Windows.Forms.Label labelNu;
        private System.Windows.Forms.Label labelNam;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBoxCMND;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxTenNV;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxMaNV;
        private Bunifu.UI.WinForms.BunifuRadioButton BtnRadioNu;
        private Bunifu.UI.WinForms.BunifuRadioButton BtnRadioNam;
        private Bunifu.Framework.UI.BunifuDatepicker DatepickerNgaySinh;
        private System.Windows.Forms.Label NgaySinh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnThem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnLuu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnXoa;
        private System.Windows.Forms.DataGridView dataGridViewNV;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBoxTimKiem;
    }
}